server:
  port: 9005
  servlet:
    context-path: /canal


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seata_order?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: canal
